# Sample configuration file for blue noise dithering

# Color distance calculation method
# Available: rgb, weighted_rgb, cie76, cie94, ciede2000, ciede2000_fast, oklab, hsv
# Recommended: ciede2000_fast (excellent quality with good performance)
# For speed: weighted_rgb, rgb
# For maximum quality: ciede2000 (slower)
color_distance_method: ciede2000_fast

# Base noise strength (0.0 to 1.0)
noise_strength: 0.5

# Adaptive noise strategy
# Individual: uniform, gradient, edge, contrast
# Combinations: gradient_edge, gradient_contrast, edge_contrast, all
# Use 'uniform' to disable adaptive noise behavior (constant noise strength)
# Recommended: gradient_edge (balanced detail preservation)
adaptive_strategy: gradient_edge

# Alpha channel handling method
# Available: threshold, dithering
alpha_method: dithering

# Alpha threshold for transparency (0.0 to 1.0)
alpha_threshold: 0.5

# Output noise strength map (optional)
# Saves adaptive noise strength as grayscale image
# White = high noise, Black = low noise, Gray = medium
# output_noise_map: noise_strength_visualization.png

# File paths (can be overridden by command line)
# palette_file: examples/sample_palette.txt
# blue_noise_file: examples/blue_noise.png